name: Push docker containers
run-name: ${{ inputs.repo_branch }} ${{ inputs.target }}

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      rootfs_url:
        description: 'Openwrt rootfs file url'
        required: true

      repo_branch:
        description: 'Openwrt repository branch/tag'
        default: "v19.07.9"
        required: true

      target:
          description: 'Openwrt repository branch/tag'
          default: "x86_64"
          required: true

env:
  DOCKER_USER: mhy123152
  DOCKER_REPO: openwrt-rootfs

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: 构造docker镜像
      id: push
      run: |
        cd $GITHUB_WORKSPACE/mydockerx86 && \
        wget -O rootfs.tar.gz ${{ github.event.inputs.rootfs_url }} && \
        chmod +x build.sh && \
        ./build.sh ${{ env.DOCKER_USER }} ${{ env.DOCKER_REPO }} ${{ github.event.inputs.target }}-${{ github.event.inputs.repo_branch }} && \
        gzip -dc docker-img-openwrt.gz | docker load && \
        docker login --username=${{ secrets.DOCKER_USER }} --password=${{ secrets.DOCKER_TOKEN }} && \
        # docker tag \
        # ${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:latest \
        # ${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:${{ github.event.inputs.target }}-${{ github.event.inputs.repo_branch }} && \
        docker push ${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:${{ github.event.inputs.target }}-${{ github.event.inputs.repo_branch }} && \
        echo "status=success" >> $GITHUB_OUTPUT